[[config]]
path = "../configs/datasets/bdd100k/pan_seg.toml"

[[config]]
path = "../configs/models/panoptic/panoptic_fpn_R_18_FPN.toml"

[model]
    [model.optimizer]
    type = "SGD"
    lr = 0.001

    [model.lr_scheduler]
    type = "StepLR"
    mode = "step"
    warmup = "exponential"
    kwargs = {"step_size" = 10}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1