[model]
type = "D2TwoStageDetector"
model_base = "faster-rcnn/r50-fpn"
weights = "detectron2"
category_mapping = {"pedestrian" = 0, "rider" = 1, "car" = 2, "truck" = 3, "bus" = 4, "train" = 5, "motorcycle" = 6, "bicycle" = 7, "traffic light" = 8, "traffic sign" = 9}
image_channel_mode = "BGR"
