version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements/install.txt
    - requirements: requirements/torch-lib.txt
    - requirements: requirements/viewer.txt

sphinx:
  configuration: docs/source/conf.py
