[[train]]
name = "bdd100k_det_sample_train"
type = "COCO"
annotations = "openmt/engine/testcases/detect/bdd100k-samples/annotation_coco.json"
data_root = "openmt/engine/testcases/detect/bdd100k-samples/images"
config_path = "openmt/engine/testcases/detect/bdd100k-samples/config.toml"
num_processes = 0

[[test]]
name = "bdd100k_det_sample_val"
type = "Scalabel"
annotations = "openmt/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "openmt/engine/testcases/detect/bdd100k-samples/images"
config_path = "openmt/engine/testcases/detect/bdd100k-samples/config.toml"
num_processes = 0
eval_metrics = ["detect"]

[dataloader]
workers_per_gpu = 0
categories = ["pedestrian", "rider", "car", "truck", "bus", "train", "motorcycle", "bicycle", "traffic light", "traffic sign"]
    [dataloader.ref_sampling_cfg]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0

    [[dataloader.train_augmentations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}

    [[dataloader.train_augmentations]]
    type = "RandomFlip"
    kwargs = {"prob" = 0.5}

    [[dataloader.train_augmentations]]
    type = "BrightnessJitterAugmentation"
    kwargs = {}

    [[dataloader.test_augmentations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}
