[model]
type = "QDTrack"
category_mapping = {"pedestrian" = 0, "rider" = 1, "car" = 2, "truck" = 3, "bus" = 4, "train" = 5, "motorcycle" = 6, "bicycle" = 7}
image_channel_mode = "BGR"
    [model.detection]
    type = "D2TwoStageDetector"
    model_base = "faster-rcnn/r50-fpn"
    model_kwargs = {"MODEL.ROI_BOX_HEAD.SMOOTH_L1_BETA" = 1.0, "MODEL.RPN.SMOOTH_L1_BETA" = 0.111, "MODEL.PIXEL_STD" = [57.375, 57.120, 58.395], "MODEL.RESNETS.NORM" = "BN"}
    set_batchnorm_eval = true
    weights = "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

    [model.track_graph]
    type = "QDTrackGraph"
    keep_in_memory = 10  # timesteps

    [[model.losses]]
    type = "MultiPosCrossEntropyLoss"
    loss_weight = 0.25

    [[model.losses]]
    type = "EmbeddingDistanceLoss"
    loss_weight = 1.0
    neg_pos_ub = 3
    pos_margin = 0
    neg_margin = 0.3
    hard_mining = true

    [model.similarity]
    type = "QDSimilarityHead"
    in_dim = 256
    num_convs = 4
    conv_out_dim = 256
    num_fcs = 1
    fc_out_dim = 1024
    embedding_dim = 256
    conv_has_bias = false
    norm = "GroupNorm"
    proposal_append_gt = true

        [model.similarity.proposal_pooler]
        type = "D2RoIPooler"
        pooling_op = "ROIAlignV2"
        resolution = [7, 7]
        strides = [4, 8, 16, 32]
        sampling_ratio = 0

        [model.similarity.proposal_sampler]
        type = "CombinedSampler"
        batch_size_per_image = 256
        positive_fraction = 0.5
        pos_strategy = "instance_balanced"
        neg_strategy = "iou_balanced"

        [model.similarity.proposal_matcher]
        type = "MaxIoUMatcher"
        thresholds = [0.3, 0.7]
        labels = [0, -1, 1]
        allow_low_quality_matches = false
