[[train]]
name = "bdd100k_track_sample_train"
type = "BDD100K"
annotations = "vist/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vist/engine/testcases/track/bdd100k-samples/images/"
config_path = "box_track"
num_processes = 0
    [train.dataloader_cfg]
    image_channel_mode = "RGB"
    [ref_sampling_cfg]
    type = 'uniform'
    scope = 2
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[transformations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}

    [[transformations]]
    type = "RandomFlip"
    kwargs = {"prob" = 0.5}

[[train]]
name = "bdd100k_det_sample_train"
type = "BDD100K"
annotations = "vist/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vist/engine/testcases/detect/bdd100k-samples/images/"
config_path = "det"
num_processes = 0
    [train.dataloader_cfg]
    image_channel_mode = "RGB"
    [ref_sampling_cfg]
    scope = 0
    num_ref_imgs = 1

    [[transformations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}

    [[transformations]]
    type = "RandomFlip"
    kwargs = {"prob" = 0.5}

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vist/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vist/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track"]
inference_sampling = "sequence_based"
config_path = "box_track"
num_processes = 0

    [test.dataloader_cfg]
    image_channel_mode = "RGB"
    [[transformations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}
