[[train]]
name = "bdd100k_track_sample_train"
type = "BDD100K"
annotations = "vist/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vist/engine/testcases/track/bdd100k-samples/images/"
config_path = "box_track"
num_processes = 0

[[train]]
name = "bdd100k_det_sample_train"
type = "BDD100K"
annotations = "vist/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vist/engine/testcases/detect/bdd100k-samples/images/"
config_path = "det"
num_processes = 0

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vist/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vist/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track"]
inference_sampling = "sequence_based"
config_path = "box_track"
num_processes = 0

[dataloader]
workers_per_gpu = 0
categories = ["pedestrian", "rider", "car", "truck", "bus", "train", "motorcycle", "bicycle"]
compute_global_instance_ids = true
    [dataloader.ref_sampling_cfg]
    type = 'uniform'
    scope = 2
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[dataloader.train_augmentations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}

    [[dataloader.train_augmentations]]
    type = "RandomFlip"
    kwargs = {"prob" = 0.5}

    [[dataloader.test_augmentations]]
    type = "Resize"
    kwargs = {"shape" = [720, 1280]}
