[[train]]
name = "bdd100k_track_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/box_track_20/train/"
data_root = "data/bdd100k/images/track/train/"
config_path = "box_track"
num_processes = 0
cache_as_binary = true
    [train.dataloader]
    skip_empty_samples = true

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5


[[test]]
name = "bdd100k_track_val"
type = "BDD100K"
annotations = "data/bdd100k/labels/box_track_20/val/"
data_root = "data/bdd100k/images/track/val/"
eval_metrics = ["track"]
config_path = "box_track"
num_processes = 0
cache_as_binary = true
    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]
