[[train]]
name = "bdd100k_tag_train"
type = "Scalabel"
annotations = "data/bdd100k/labels/det_20/det_train.json"
data_root = "data/bdd100k/images/100k/train/"
config_path = "configs/base/datasets/configs/bdd100k_weather_tagging.toml"
cache_as_binary = true
num_processes = 0
tagging_attribute = "weather"
    [train.sample_mapper]
    fields_to_load = ["image_tags"]

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [640, 640]

[[test]]
name = "bdd100k_tag_val"
type = "Scalabel"
annotations = "data/bdd100k/labels/det_20/det_val.json"
data_root = "data/bdd100k/images/100k/val/"
config_path = "configs/base/datasets/configs/bdd100k_weather_tagging.toml"
cache_as_binary = true
num_processes = 0
eval_metrics = ["tagging"]
tagging_attribute = "weather"
    [test.sample_mapper]
    fields_to_load = ["image_tags"]

    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "CenterCrop"
    kwargs = {"size" = [640, 640]}
