[[train]]
name = "bdd100k_tag_train"
type = "Scalabel"
annotations = "data/bdd100k/labels/det_20/det_train.json"
data_root = "data/bdd100k/images/100k/train/"
config_path = "configs/base/datasets/configs/bdd100k_tagging.toml"
cache_as_binary = true
num_processes = 0
category_mapping = [{"rainy" = 0, "snowy" = 1, "clear" = 2, "overcast" = 3, "undefined" = 4, "partly cloudy" = 5, "foggy" = 6}, {"tunnel" = 0, "residential" = 1, "parking lot" = 2, "undefined" = 3, "city street" = 4, "gas stations" = 5, "highway" = 6}]
tagging_attribute = ["weather", "scene"]
    [train.sample_mapper]
    fields_to_load = ["image_tags"]

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    shape = [640, 640]

[[test]]
name = "bdd100k_tag_val"
type = "Scalabel"
annotations = "data/bdd100k/labels/det_20/det_val.json"
data_root = "data/bdd100k/images/100k/val/"
config_path = "configs/base/datasets/configs/bdd100k_tagging.toml"
cache_as_binary = true
num_processes = 0
eval_metrics = ["tagging"]
category_mapping = [{"rainy" = 0, "snowy" = 1, "clear" = 2, "overcast" = 3, "undefined" = 4, "partly cloudy" = 5, "foggy" = 6}, {"tunnel" = 0, "residential" = 1, "parking lot" = 2, "undefined" = 3, "city street" = 4, "gas stations" = 5, "highway" = 6}]
tagging_attribute = ["weather", "scene"]
    [test.sample_mapper]
    fields_to_load = ["image_tags"]

    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "CenterCrop"
    kwargs = {"size" = [640, 640]}
