[[train]]
name = "bdd100k_pan_seg_train"
type = "Scalabel"
annotations = "data/bdd100k/labels/pan_seg_train_rle.json"
data_root = "data/bdd100k/images/hdf5s/10k_train.hdf5"
config_path = "configs/base/configs/pan_seg.toml"
num_processes = 0
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks", "semantic_masks"]

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_pan_seg_val"
type = "Scalabel"
annotations = "data/bdd100k/labels/pan_seg_val_rle.json"
data_root = "data/bdd100k/images/hdf5s/10k_val.hdf5"
config_path = "configs/base/configs/pan_seg.toml"
eval_metrics = ["pan_seg"]
num_processes = 0
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks", "semantic_masks"]

    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
