[[train]]
name = "coco_det_train"
type = "COCO"
annotations = "data/COCO/annotations/instances_train2017.json"
data_root = "data/COCO/train2017"
    [train.sample_mapper]
    skip_empty_samples = true

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [800, 1333]
    keep_ratio = true

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "coco_det_val"
type = "COCO"
annotations = "data/COCO/annotations/instances_val2017.json"
data_root = "data/COCO/val2017"
eval_metrics = ["detect"]
    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [800, 1333]
    keep_ratio = true