[[train]]
name = "motchallenge_sample_train"
type = "MOTChallenge"
annotations = "data/MOT16"
data_root = "data/MOT16"

[[test]]
name = "motchallenge_sample_val"
type = "MOTChallenge"
annotations = "data/MOT16"
data_root = "data/MOT16"
eval_metrics = ["track"]
inference_sampling = "sequence_based"

[dataloader]
workers_per_gpu = 2
categories = ["pedestrian"]
skip_empty_samples = true
    [dataloader.data_backend]
    type = "FileBackend"
    [dataloader.ref_sampling_cfg]
    type = 'uniform'
    scope = 3
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[dataloader.train_augmentations]]
    type = "Resize"
    kwargs = {"shape" = [1080, 1920]}

    [[dataloader.train_augmentations]]
    type = "RandomFlip"
    kwargs = {"prob" = 0.5}

    [[dataloader.test_augmentations]]
    type = "Resize"
    kwargs = {"shape" = [1080, 1920]}
