[[train]]
name = "shift_3dtrack_train"
type = "SHIFTDataset"
annotations = "data/SHIFT/mot/img_center/image_center_box3d.train.json"
attributes = {"weather" = ["clear"], "timeofday" = ["daytime"]}
data_root = "data/SHIFT/mot/img_center/data.hdf5"

num_processes = 0
cache_as_binary = true
    [train.dataloader]
    skip_empty_samples = true
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [train.dataloader.ref_sampling]
    type = 'uniform'
    scope = 3
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [train.dataloader.data_backend]
    type = "HDF5Backend" 

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5


[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"weather" = ["clear"], "timeofday" = ["daytime"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]

[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"weather" = ["partly cloudy"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]

[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"weather" = ["overcast"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]


[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"weather" = ["foggy"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]


[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"weather" = ["rainy"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]

[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"timeofday" = ["dawn/dusk"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]

[[test]]
name = "carla_3dtrack_val"
type = "CarlaDataset"
annotations = "data/dist/mot/img_center/image_center_box3d.val.json"
attributes = {"timeofday" = ["night"]}
data_root = "/cluster/work/cvl/mnaeem/CarlaData/dist/mot/img_center/data.hdf5"
eval_metrics = ["detect", "track"]
num_processes = 0
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics"]

    [test.dataloader.data_backend]
    type = "HDF5Backend" 

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [800, 1280]