[[train]]
name = "waymo_sample_train"
type = "Waymo"
data_root = "data/Waymo_scalabel"
input_dir = "data/Waymo/train"
output_dir = "data/Waymo_scalabel"
num_processes = 0
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]
    skip_empty_samples = true

    [train.ref_sampler]
    scope = 3
    num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [1080, 1920]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [1080, 1920]


[[test]]
name = "waymo_sample_val"
type = "Waymo"
data_root = "data/Waymo_scalabel"
input_dir = "data/Waymo/train"
output_dir = "data/Waymo_scalabel"
eval_metrics = ["track"]
num_processes = 0
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [1080, 1920]

