name: "🚀Feature Request"
description: Suggest an idea for this project
labels: enhancement, help wanted

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: feature
    attributes:
      label: Describe the Feature
      description: A clear and concise description of the feature proposal.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: A clear and concise description of what the problem is. If this is related to another GitHub issue, please link here too.

  - type: textarea
    id: pitch
    attributes:
      label: Pitch
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered, if any.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
