[detection]
model_base = "retinanet/r50-fpn"
weights = "detectron2"
num_classes = 10
device = "cpu"

[solver]
images_per_batch = 1
lr_policy = "WarmupMultiStepLR"
base_lr = 0.02
max_iters = 1

[[train]]
name = "sample_train"
type = "coco"
annotation_file = "systm/detect/testcases/bdd100k_sample/annotation.json"
data_root = "systm/detect/testcases/bdd100k_sample/"

[[test]]
name = "sample_val"
type = "coco"
annotation_file = "systm/detect/testcases/bdd100k_sample/annotation.json"
data_root = "systm/detect/testcases/bdd100k_sample/"

[dataloader]
num_workers = 16

[launch]
num_gpus=0