[detection]
model_base = "retinanet/r50-fpn"
weights = "detectron2"
num_classes = 10
device = "cpu"

[solver]
images_per_batch = 1
lr_policy = "WarmupMultiStepLR"
base_lr = 0.02
max_iters = 1
steps = [100]
checkpoint_period = 100
eval_period = 100

[[train]]
name = "sample_train"
type = "coco"
annotation_file = "openmt/detect/testcases/bdd100k-samples/annotation.json"
data_root = "openmt/detect/testcases/bdd100k-samples/"

[[test]]
name = "sample_val"
type = "coco"
annotation_file = "openmt/detect/testcases/bdd100k-samples/annotation.json"
data_root = "openmt/detect/testcases/bdd100k-samples/"

[dataloader]
num_workers = 2

[launch]
num_gpus=0
