[[config]]
path = "../configs/datasets/shift/rgbd_track.toml"

[[config]]
path = "../configs/models/mmdetection/qd3dt_R_18_FPN.toml"

[model]
category_mapping = {"bicycle" = 0, "car" = 1, "motor" = 2, "truck" = 3}
    [model.optimizer]
    type = "SGD"
    lr = 0.001
    warmup_steps = 1000
    kwargs = {"momentum" = 0.9, "weight_decay" = 0.0001}

    [model.lr_scheduler]
    type = "MultiStepLR"
    kwargs = {"milestones" = [8, 11]}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_epochs = 12
log_every_n_steps = 50
check_val_every_n_epoch = 1
num_sanity_val_steps = 2