[[config]]
path = "../configs/datasets/bdd100k/track.toml"

[train_handler]

    [[train_handler.transformations]]
    type = "Mosaic"
    out_shape = [720, 1280]

    [[train_handler.transformations]]
    type = "MixUp"
    out_shape = [720, 1280]

    [[train_handler.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train_handler.transformations]]
    type = "Resize"
    shape = [720, 1280]
    keep_ratio = true

[[config]]
path = "../configs/models/detectron2/qdtrack_R_50_FPN.toml"

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1
check_val_every_n_epoch = 10