[model]
type = "MMEncDecSegmentor"
category_mapping = {"road" = 0, "sidewalk" = 1, "building" = 2, "wall" = 3, "fence" = 4, "pole" = 5, "traffic light" = 6, "traffic sign" = 7, "vegetation" = 8, "terrain" = 9, "sky" = 10, "person" = 11, "rider" = 12, "car" = 13, "truck" = 14, "bus" = 15, "train" = 16, "motorcycle" = 17, "bicycle" = 18}
model_base = "mmseg://_base_/models/deeplabv3_r50-d8.py"
model_kwargs= {"pretrained" = "open-mmlab://resnet18_v1c", "backbone.depth" = 18, "backbone.norm_cfg.type" = "BN", "decode_head.norm_cfg.type" = "BN", "decode_head.in_channels" = 512, "decode_head.channels" = 128, "auxiliary_head.norm_cfg.type" = "BN", "auxiliary_head.in_channels" = 256, "auxiliary_head.channels" = 64}
pixel_mean = [123.675, 116.28, 103.53]
pixel_std = [58.395, 57.12, 57.375]
weights = "mmseg://deeplabv3/deeplabv3_r18-d8_512x1024_80k_cityscapes/deeplabv3_r18-d8_512x1024_80k_cityscapes_20201225_021506-23dffbe2.pth"
