[model]
type = "MMTwoStageDetector"
category_mapping = {"pedestrian" = 0, "rider" = 1, "car" = 2, "truck" = 3, "bus" = 4, "train" = 5, "motorcycle" = 6, "bicycle" = 7, "traffic light" = 8, "traffic sign" = 9}
model_base = "vis4d/engine/testcases/configs/models/mmdetection/mmdet_cfg_frcnn_r18fpn.py"
pixel_mean = [123.675, 116.28, 103.53]
pixel_std = [58.395, 57.12, 57.375]
    [model.backbone]
    type = "DLA"
    name = "dla34"
    weights = "dla://dla34"
    out_indices = [2, 3, 4, 5]

    [model.backbone.neck]
    type = "MMDetNeck"
        [model.backbone.neck.mm_cfg]
        type = "FPN"
        in_channels = [64, 128, 256, 512]
        out_channels = 64
        num_outs= 5