[model]
type = "MMTwoStageDetector"
category_mapping = {"pedestrian" = 0, "rider" = 1, "car" = 2, "truck" = 3, "bus" = 4, "train" = 5, "motorcycle" = 6, "bicycle" = 7}
model_base = "vis4d/engine/testcases/configs/models/mmdetection/mmdet_cfg_maskrcnn_r18fpn.py"
pixel_mean = [123.675, 116.28, 103.53]
pixel_std = [58.395, 57.12, 57.375]
