[imageSize]
height = 720
width = 1280

[[categories]]
name = "weather"
    [[categories.subcategories]]
    name = "rainy"

    [[categories.subcategories]]
    name = "snowy"

    [[categories.subcategories]]
    name = "clear"

    [[categories.subcategories]]
    name = "overcast"

    [[categories.subcategories]]
    name = "undefined"

    [[categories.subcategories]]
    name = "partly cloudy"

    [[categories.subcategories]]
    name = "foggy"