[[config]]
path = "../configs/datasets/kitti/track.toml"

[[config]]
path = "../configs/models/mmdetection/qdtrack_R_50_FPN.toml"

[model.detection]
num_classes = 3

[solver]
images_per_gpu = 1
lr_policy = "WarmupMultiStepLR"
base_lr = 0.01
warmup_iters = 0
steps = []
max_iters = 1
log_period = 1
checkpoint_period = 1000
eval_period = 100
