[model]
type = "MMImageClassifier"
tagging_attribute = "weather"
category_mapping = {"rainy" = 0, "snowy" = 1, "clear" = 2, "overcast" = 3, "undefined" = 4, "partly cloudy" = 5, "foggy" = 6}
model_base = "mmcls://_base_/models/resnet18.py"
model_kwargs= {"head.num_classes" = 7}
pixel_mean = [123.675, 116.28, 103.53]
pixel_std = [58.395, 57.12, 57.375]
weights = "mmcls://resnet/resnet18_batch256_imagenet_20200708-34ab8f90.pth"