[[config]]
path = "../configs/datasets/bdd100k/detect.toml"

[[config]]
path = "../configs/models/detectron2/faster_rcnn_R_50_FPN.toml"

[solver]
images_per_gpu = 1
lr_policy = "WarmupMultiStepLR"
base_lr = 0.01
max_iters = 1
warmup_iters = 0
steps = []
checkpoint_period = 100
log_period = 1
eval_period = 100
