[model]
type = "test-model"

[solver]
images_per_gpu = 16
lr_policy = "step"
base_lr = 0.02
steps = [1000, 2000]
max_iters = 10000
eval_metrics = []

[dataloader]
workers_per_gpu = 16
    [dataloader.ref_sampling_cfg]
    type = 'uniform'
    scope = 2
    num_ref_imgs = 1