data:
  experiment: "bdd100k"

model:
  category_mapping:
    pedestrian: 0
  detection:
    class_path: vis4d.model.detect.MMTwoStageDetector
    init_args:
      category_mapping:
        pedestrian: 0
      model_base: "mmdet://faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py"
      pixel_mean: [123.675, 116.28, 103.53]
      pixel_std: [58.395, 57.12, 57.375]
      backbone_output_names: ["p2", "p3", "p4", "p5", "p6"]
  similarity:
    class_path: vis4d.model.track.similarity.QDSimilarityHead
  track_graph:
    class_path: vis4d.model.track.graph.QDTrackGraph
    init_args:
      keep_in_memory: 10

  optimizer_init:
    class_path: torch.optim.SGD
    init_args:
      lr: 0.02
      momentum: 0.9
      weight_decay: 0.0001

  lr_scheduler_init:
    class_path: torch.optim.lr_scheduler.MultiStepLR
    init_args:
      milestones: [8, 11]
