[[train]]
name = "bdd100k_ins_seg_sample_train"
type = "COCO"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation_coco.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/detect/bdd100k-samples/ins_seg_config.toml"
num_processes = 0
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [
        [360, 640],
        [480, 960]
    ]
    keep_ratio = true
    multiscale_mode = "list"

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    crop_type = "relative_range"
    shape = [[0.4, 0.5], [0.5, 0.6]]
    allow_empty_crops = false
    recompute_boxes2d = true

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.sample_mapper.transformations]]
    type = "KorniaColorJitter"
    prob = 0.5
    kwargs = {"brightness" = [0.8, 1.2], "contrast" = [0.8, 1.2], "saturation" = [0.8, 1.2]}

[[test]]
name = "bdd100k_ins_seg_sample_val"
type = "Scalabel"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/detect/bdd100k-samples/ins_seg_config.toml"
num_processes = 0
eval_metrics = ["detect", "ins_seg"]
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
