[[train]]
name = "bdd100k_ins_seg_sample_train"
type = "COCO"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation_coco.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/detect/bdd100k-samples/config.toml"
num_processes = 0
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

    [train.ref_sampler]
    strategy = 'uniform'
    scope = 0
    num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]

[[train]]
name = "bdd100k_sem_seg_sample_train"
type = "Scalabel"
annotations = "vis4d/engine/testcases/segment/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/segment/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/segment/bdd100k-samples/config.toml"
num_processes = 0
    [train.sample_mapper]
    fields_to_load = ["semantic_masks"]

    [train.ref_sampler]
    scope = 1
    num_ref_imgs = 0

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track"]
config_path = "box_track"
num_processes = 0
    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
