[[train]]
name = "bdd100k_sem_seg_sample_train"
type = "BDD100K"
annotations = "vis4d/engine/testcases/segment/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/segment/bdd100k-samples/images"
config_path = "sem_seg"
num_processes = 0
category_mapping = {"road" = 0, "sidewalk" = 1, "building" = 2, "wall" = 3, "fence" = 4, "pole" = 5, "traffic light" = 6, "traffic sign" = 7, "vegetation" = 8, "terrain" = 9, "sky" = 10, "person" = 11, "rider" = 12, "car" = 13, "truck" = 14, "bus" = 15, "train" = 16, "motorcycle" = 17, "bicycle" = 18, "background" = 19}
    [train.sample_mapper]
    fields_to_load = ["semantic_masks"]
    background_as_class = true

    [train.ref_sampler]
    scope = 1
    num_ref_imgs = 0

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]

[[train]]
name = "bdd100k_seg_track_sample_train"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
config_path = "seg_track"
num_processes = 0
cache_as_binary = true
compute_global_instance_ids = true
category_mapping = {"pedestrian" = 0, "rider" = 1, "car" = 2, "truck" = 3, "bus" = 4, "train" = 5, "motorcycle" = 6, "bicycle" = 7}
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

    [train.ref_sampler]
    strategy = 'uniform'
    scope = 2
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track"]
config_path = "box_track"
num_processes = 0
    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
