[[train]]
name = "bdd100k_tag_sample_train"
type = "Scalabel"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/tagging/bdd100k-samples/weather.toml"
num_processes = 0
tagging_attr = "weather"
    [train.sample_mapper]
    fields_to_load = ["image_tags"]

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    shape = [640, 640]

[[test]]
name = "bdd100k_tag_sample_val"
type = "Scalabel"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/tagging/bdd100k-samples/weather.toml"
num_processes = 0
eval_metrics = ["tagging"]
tagging_attr = "weather"
    [test.sample_mapper]
    fields_to_load = ["image_tags"]

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [640, 640]
