[[train]]
name = "bdd100k_tag_sample_train"
type = "Scalabel"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/tagging/bdd100k-samples/config.toml"
num_processes = 0
category_mapping = [{"rainy" = 0, "snowy" = 1, "clear" = 2, "overcast" = 3, "undefined" = 4, "partly cloudy" = 5, "foggy" = 6}, {"tunnel" = 0, "residential" = 1, "parking lot" = 2, "undefined" = 3, "city street" = 4, "gas stations" = 5, "highway" = 6}]
tagging_attribute = ["weather", "scene"]
    [train.sample_mapper]
    fields_to_load = ["image_tags"]

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    shape = [640, 640]

[[test]]
name = "bdd100k_tag_sample_val"
type = "Scalabel"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/tagging/bdd100k-samples/config.toml"
num_processes = 0
eval_metrics = ["tagging"]
category_mapping = [{"rainy" = 0, "snowy" = 1, "clear" = 2, "overcast" = 3, "undefined" = 4, "partly cloudy" = 5, "foggy" = 6}, {"tunnel" = 0, "residential" = 1, "parking lot" = 2, "undefined" = 3, "city street" = 4, "gas stations" = 5, "highway" = 6}]
tagging_attribute = ["weather", "scene"]
    [test.sample_mapper]
    fields_to_load = ["image_tags"]

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [640, 640]
