[[train]]
name = "bdd100k_track_sample_train"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
config_path = "box_track"
num_processes = 0
cache_as_binary = true
compute_global_instance_ids = true
    [train.sample_mapper]
        [train.ref_sampler]
        strategy = 'uniform'
        scope = 2
        num_ref_imgs = 1
        skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[train]]
name = "bdd100k_det_sample_train"
type = "BDD100K"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images/"
config_path = "det"
num_processes = 0
cache_as_binary = true
    [train.sample_mapper]
        [train.ref_sampler]
        scope = 0
        num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track"]
config_path = "box_track"
num_processes = 0
cache_as_binary = true
    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
