[[train]]
name = "bdd100k_track_sample_train"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
config_path = "box_track"
num_processes = 0
cache_as_binary = true

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["track"]
config_path = "box_track"
num_processes = 0
cache_as_binary = true
    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]
